version: '3.3'
networks:
  tower-defense:
    name: "network-elastic"
    driver_opts:
      icc: "true"
    driver: bridge
    
services:

  # ElasticSearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - ELASTIC_PASSWORD=dangtuan12
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - path.data=/usr/share/elasticsearch/data
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    stdin_open: true
    tty: true
    networks:
      - tower-defense
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  # Kibana Service 
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.10
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD="dangtuan12"
      - ELASTICSEARCH_URL=http://localhost:9200
      - SERVER_NAME=my-kibana
      - XPACK_SECURITY_ENABLED=true
      - PATH_DATA=/usr/share/kibana/data
    volumes:
      - ./kibana/data:/usr/share/kibana/data
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    networks:
      - tower-defense
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  # Logstash Service        
  # logstash:
  #   container_name: logstash
  #   image: docker.elastic.co/logstash/logstash:7.17.10

  #   environment:
  #     - ELASTICSEARCH_USERNAME=elastic
  #     - ELASTICSEARCH_PASSWORD="dangtuan12"
  #     - NODE_NAME=my-logstash
  #     - XPACK_MONITORING_ENABLED=true
  #     # - "LS_JAVA_OPTS=-Xms8192m -Xmx8192m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ./logstash/logstash.template.json:/usr/share/logstash/templates/logstash.template.json
  #   ports:
  #     - 5044:5044
  #   links:
  #     - elasticsearch:elasticsearch
  #   depends_on:
  #     - elasticsearch
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - tower-defense
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "50"
